const imageMap: Record<string, any> = {
    "p_1/FotoProducto1.jpeg": require("../assets/products/p_1/FotoProducto1.jpeg"),
    "p_2/FotoProducto2.jpeg": require("../assets/products/p_2/FotoProducto2.jpeg"),
    "p_3/FotoProducto3.jpeg": require("../assets/products/p_3/FotoProducto3.jpeg"),
    "p_4/FotoProducto4.jpeg": require("../assets/products/p_4/FotoProducto4.jpeg"),
    "p_5/FotoProducto5.jpeg": require("../assets/products/p_5/FotoProducto5.jpeg"),
    "p_6/FotoProducto6.jpeg": require("../assets/products/p_6/FotoProducto6.jpeg"),
    "p_7/FotoProducto7.jpeg": require("../assets/products/p_7/FotoProducto7.jpeg"),
    "p_8/FotoProducto8.jpeg": require("../assets/products/p_8/FotoProducto8.jpeg"),
    "p_9/FotoProducto9.jpeg": require("../assets/products/p_9/FotoProducto9.jpeg"),
    "p_10/FotoProducto10.jpeg": require("../assets/products/p_10/FotoProducto10.jpeg"),
    "p_11/FotoProducto11.jpeg": require("../assets/products/p_11/FotoProducto11.jpeg"),
    "p_12/FotoProducto12.jpeg": require("../assets/products/p_12/FotoProducto12.jpeg"),
    "p_13/FotoProducto13.jpeg": require("../assets/products/p_13/FotoProducto13.jpeg"),
    "p_14/FotoProducto14.jpeg": require("../assets/products/p_14/FotoProducto14.jpeg"),
    "p_15/FotoProducto15.jpeg": require("../assets/products/p_15/FotoProducto15.jpeg"),
    "p_16/FotoProducto16.jpeg": require("../assets/products/p_16/FotoProducto16.jpeg"),
    "p_17/FotoProducto17.jpeg": require("../assets/products/p_17/FotoProducto17.jpeg"),
    "p_18/FotoProducto18.jpeg": require("../assets/products/p_18/FotoProducto18.jpeg"),
    "p_19/FotoProducto19.jpeg": require("../assets/products/p_19/FotoProducto19.jpeg"),
    "p_20/FotoProducto20.jpeg": require("../assets/products/p_20/FotoProducto20.jpeg"),
    "p_21/FotoProducto21.jpeg": require("../assets/products/p_21/FotoProducto21.jpeg"),
    "p_22/FotoProducto22.jpeg": require("../assets/products/p_22/FotoProducto22.jpeg"),
    "p_23/FotoProducto23.jpeg": require("../assets/products/p_23/FotoProducto23.jpeg"),
    "p_24/FotoProducto24.jpeg": require("../assets/products/p_24/FotoProducto24.jpeg"),
    "p_25/FotoProducto25.jpeg": require("../assets/products/p_25/FotoProducto25.jpeg"),
    "p_26/FotoProducto26.jpeg": require("../assets/products/p_26/FotoProducto26.jpeg"),
    "p_27/FotoProducto27.jpeg": require("../assets/products/p_27/FotoProducto27.jpeg"),
    "p_28/FotoProducto28.jpeg": require("../assets/products/p_28/FotoProducto28.jpeg"),
    "p_29/FotoProducto29.jpeg": require("../assets/products/p_29/FotoProducto29.jpeg"),
    "p_30/FotoProducto30.jpeg": require("../assets/products/p_30/FotoProducto30.jpeg"),
  };
  
  export default imageMap;
  